import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{children: React.ReactNode;}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="flex justify-around items-center py-[1rem] bg-gray-200">
          <Image
            className="dark:invert"
            src="/next.svg"
            alt="account menu"
            width={100}
            height={20}
            priority
          />
          <nav className="flex">
            <button>
              <Image
                className="dark:invert"
                src="/globe.svg"
                alt="account menu"
                width={20}
                height={20}
                priority
              />
            </button>
            <ul className="hidden">
              <li>menu</li>
              <li>menu</li>
              <li>menu</li>
            </ul>
          </nav>
        </header>
        {children}
        <footer>
          <small className="block text-center bg-gray-200 py-[.5rem]">copyright</small>
        </footer>
      </body>
    </html>
  );
}
